### ISSUE TITLE
Compile PyPI instructions

### ISSUE THREAD

**Issue by iangow** [iangow/wrds2pg#1]
Put these in a comment here.

**Comment by iangow** [comment]
Code seems to work (see #2).

**Comment by jingyujzhang** [comment]
The new library is available [here](https://pypi.org/project/wrds2pg/). The README is **almost** the same with the README in this repo.

**Comment by jingyujzhang** [comment]
### Generate distribution archives
Make sure you have the latest versions of `setuptools` and `wheel` installed:
```bash
python3 -m pip install --user --upgrade setuptools wheel
```
Now run this command from the same directory where `setup.py` is located:
```py
python3 setup.py sdist bdist_wheel
```
This command should output a lot of text and once completed should generate two files in the `dist` directory:
```bash
dist/
  example_pkg_your_username-0.0.1-py3-none-any.whl
  example_pkg_your_username-0.0.1.tar.gz
```
### Upload the distribution archives
Now that you are registered, you can use [twine](https://packaging.python.org/key_projects/#twine) to upload the distribution packages. You’ll need to install Twine:
```
python3 -m pip install --user --upgrade twine
```
Once installed, run Twine to upload all of the archives under `dist`:
```
python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
```
The command above will upload the package to `test.pypi`.  Use this command to upload it to `pypi`.
```
twine upload dist/*
```
### Install newly uploaded package
Install the package from TestPyPI:
```
python3 -m pip install --index-url https://test.pypi.org/simple/ --no-deps wrds2pg
```
Install the package form PyPI:
```
pip3 install wrds2pg
```
The official document is [here](https://packaging.python.org/tutorials/packaging-projects/).
