### ISSUE TITLE
Add ability to suppress role creation

### ISSUE THREAD

**Issue by iangow** [iangow/wrds2pg#18]
Some users lack `CREATE ROLE` privileges.

**Comment by iangow** [comment]
@EvanJo Done. New argument `create_roles` has a default of `True`, but if set to `False`, no roles will be created (and ownership will be the default of the user creating the table). I do assume `CREATE SCHEMA` privileges, but (I believe) these can exist at the database level unlike `CREATE ROLE` privileges.

I have not yet pushed to PyPI, but one can install using `pip install git+https://github.com/iangow/wrds2pg --upgrade`.

**Comment by EvanJo** [comment]
Thanks a ton! Pulled and it works great!
