### ISSUE TITLE
`res` is not assigned when `create_roles=False`.

### ISSUE THREAD

**Issue by iangow** [iangow/wrds2pg#25]
See https://github.com/iangow/wrds2pg/commit/0e2e31a1fd7742e0c98bf52189ac85d95893fa0d#diff-1cbd4b08e63b27c85acbad828963235c5d8f234d130918c64d6835d04c2f101e

**Comment by iangow** [comment]
@EvanJo This version is now on PyPI. Please let me know if it breaks anything.

**Comment by EvanJo** [comment]
Thanks for the quick response! New install from PyPI works great!
