### ISSUE TITLE
wrds_to_parquet seg fault

### ISSUE THREAD

**Issue by EvanJo** [iangow/wrds2pg#29]
![Screenshot from 2023-12-05 15-21-07](https://github.com/iangow/wrds2pg/assets/5580070/1b295929-bcd5-4022-ba60-4f068b7bfe39)

Seg fault when converting temporary csv to parquet. I'm not familliar with duckdb and am not sure how to debug. Is this a memory issue? Does `memory_limit` need to be passed to duckdb connect?

That said, saving the .csv.gz files might be useful for data.table users, since it can go straight into fread() while still enjoying compression.

**Comment by iangow** [comment]
I haven't pushed the new version to PyPI, but you should be able to install it using this

```
pip install git+https://github.com/iangow/wrds2pg.git@master
```

It seems that even `wrds_to_csv()` requires a lot of RAM. But maybe try using that, then running `csv_to_pq()` separately to see what it does to RAM on your machine.

**Comment by iangow** [comment]
There must be some way to rejigger this to not need RAM.

https://github.com/iangow/wrds2pg/blob/fb4c3545e54dd0d9aa9827286ae87f2f9a8001c4/wrds2pg/wrds2pg.py#L710-L726

**Comment by iangow** [comment]
The `get_wrds_process()` is used in `wrds_update()` and is RAM-friendly there. Basically pipes data direct from SAS to PostgreSQL.

**Comment by EvanJo** [comment]
wrds_to_csv is perfect. all the segfaults happened during the parquet conversion. I'm seeing pretty good compression with gz and pretty good fread() speed. I modified wrds_to_csv slightly to piggy back off of the same file structure and last-modified functionality (stored in mtime).

**Comment by iangow** [comment]
Superseded by #34.

**Comment by iangow** [comment]
I think the right way to address this would be to have the option to split data into multiple CSV files that then get converted into multiple parquet files. Once the package is cleaned up (over the next few weeks), this should be quite feasible. For example, an optional `rows_per_file` argument or something is probably (relatively) easy to handle.

**Comment by iangow** [comment]
@EvanJo See [here](https://gist.github.com/iangow/2d8f7be06fea688ec9b84bc45c6c473a) for a prototype approach that does conversion to parquet (from PostgreSQL) without burning through RAM. It seems this could be adapted for incorporation in `wrds2pg`.

**Comment by iangow** [comment]
@EvanJo Now on [PyPI](https://pypi.org/project/db2pq/): 

```
pip install db2pg
```

Still working on fixing the `README`.

**Comment by EvanJo** [comment]
Thanks！ For now im pretty happy with compressed CSVs. I haven't found a use case for me where the parquet files did significantly better than the compressed CSVs.

**Comment by iangow** [comment]
That is surprising; maybe they're all fast. Beyond performance, I think a benefit of parquet might be the typing of columns. But if it ain't broke …

That said, I did some behind-the-scenes work in the SAS code so that `PROC EXPORT` now emits ISO 8601 compliant date-times, etc. This probably helps with the CSVs too.

https://github.com/iangow/wrds2pg/blob/d2720e151af40bfd4598fd4134e6cf305773c236/wrds2pg/wrds2pg.py#L336-L342

**Comment by iangow** [comment]
> Thanks！ For now im pretty happy with compressed CSVs. I haven't found a use case for me where the parquet files did significantly better than the compressed CSVs.

@EvanJo Are you still using compressed CSVs? I haven't touched `wrds2pq` in a couple of years. The `db2pq` library has seen more development. It only supports parquet files, but it's much faster (and memory-friendly) for downloads and has some other nice features (e.g., archiving existing data files).

**Comment by EvanJo** [comment]
I haven't touched it since. I was trying different things for an in-between solution for teaching, but ended up giving up (I just provided a cleaned CSV to undergrads and required that grad students set up their own PostgreSQL locally).

This is useful news! I may try this again next Fall. As I'm porting my materials from R to Python, I'd like to make some changes and have the undergrads dig a bit deeper merging / cleaning raw data.

**Comment by iangow** [comment]
My [book](https://iangow.github.io/far_book/) was originally premised on students using the WRDS PostgreSQL server. In practice, I ran local servers for myself (in writing the book) and for students without WRDS IDs. But the last time I taught the course, I just gave students the Parquet files in a Dropbox folder and told them to use the `parquet` variants of the code in the book and of the [templates](https://github.com/iangow/far_templates/blob/main/README.md). The parquet approach is much faster and easier for students.

I have translated some of the book chapters to Python. Once you get to larger data, I think it makes sense to use Ibis rather than pandas. If you're interested to see how one can do this, let me know. (I think pandas has some real wrinkles for students relative to R, but the "cool kids" use Python ….)

**Comment by EvanJo** [comment]
Im also facing the "cool kids use python" trend. Porting material to Python seemed fine but teaching it feels  harder for non technical students, as R was more forgiving / beginner friendly.

I think your benchmarking on duckdb+parquet just convinced me to give this another go. Then I could "use python" the same way I used to "use SAS", where most lines started with PROC SQL...

**Comment by iangow** [comment]
I'm done a crash course re(?)learning pandas in the last few weeks. I do think it's tougher than R. I wonder if you couldn't just "skip ahead" to Polars (no indexes!). But pandas seems hard to avoid. I have several chapters on my book that I've translated to Python, but it's mostly Ibis (to work with PostgreSQL, etc). But Polars might be a good middle ground.

**Comment by EvanJo** [comment]
Exactly. This is the first time students touch coding, and I want to spend more time on interesting applications in finance rather than on explaining why they need .copy().

Polars is a very interesting option, I will look into it!

Have you had an experience with python datatable?

**Comment by iangow** [comment]
> Have you had an experience with python datatable?

No. A bit with Ibis and now learning Polars. Ibis works nice with DuckDB. I have examples in my "notes" repository on GitHub. Because a lot of these use parquet files, they can be adapted to anything.

**Comment by EvanJo** [comment]
So I'm now very much sold on parquet + DuckDB for teaching.

Reading appendix E to your book, it sounds like WRDS Postgres data types are better than they used to be (Small ptsd flash back to when I was pgdumping from WRDS, eg problems with leading zero on gvkeys).

Are you largely happy with db2pq and default col_types? Might you have a reference for a col_types dictionary?

**Comment by iangow** [comment]
> So I'm now very much sold on parquet + DuckDB for teaching.
> 
> Reading appendix E to your book, it sounds like WRDS Postgres data types are better than they used to be (Small ptsd flash back to when I was pgdumping from WRDS, eg problems with leading zero on gvkeys).
> 
> Are you largely happy with db2pq and default col_types? Might you have a reference for a col_types dictionary?

"Back in the day" (i.e., as far back as 2011 and as recent as about 2019), I got WRDS data from the SAS files. SAS only really has two data types (character and floating-point) and so I would infer types from the "format" that WRDS applied to the data. But WRDS wasn't always consistent in applying these.

I used PostgreSQL for everything and each time I added data to my database, I (tried to) keep a script for it. Those scripts are found [here](https://github.com/iangow/wrds_pg).

With PostgreSQL, WRDS has is somewhat forced to do better with data types. For the longest time they were sloppy (e.g., `permno` on `crsp.dsf` and friends was stored as the equivalent of R's `double`). 

WRDS has mostly fixed those issues, but not all. They still insist on using the `TIMESTAMP WITHOUT TIME ZONE` type (a timestamp is meaningless without a time zone and most of the time it's possible to figure this out … I'd guess that TAQ data would be all `America/New_York`). And they didn't fix `lpermno` and `lpermco` in the link tables (see my script [here](https://iangow.github.io/far_book/parquet-wrds.html#sec-make-pq-pg)). (I wrote a bit about timestamps [here](https://github.com/iangow/notes/blob/main/datetimes.pdf) and I will revisit the topic in something I will post soon on curating Call Report data for US financial institutions.)

In some cases, WRDS has really fixed the data types. So CRSP data uses the `DECIMAL` types that allow one to express `234.56` as exactly that, not some floating-point approximation. This is actually a problem for things like pandas that have limited support for these types (either the package itself or downstream packages (`statsmodels`, etc.) that assume that a pandas `DataFrame` is just a collection of `np.ndarray` types in disguise. (I guess everything will break with Pandas 3.0, which is perhaps the pandas team's way of getting things to move past NumPy limitations.)

If unsure for a particular table, you could always grab a few rows using `db2pq` and check the types, perhaps using the `wrds_pg` scripts as a reference.

Regarding `gvkey`, I just keep it as `text` everywhere, as that's how the data are stored in Compustat on WRDS. If someone gives you a CSV with GVKEYs as integers, it's easy to convert in any tool. The one that is more of a pain is CIKs, which even SEC can't make up its mind on. Sometimes 10-character strings, sometimes integers. I can't remember what I do in [Chapter 23](https://iangow.github.io/far_book/glms.html#application-complexity-and-voluntary-disclosure) (the one place I use CIKs in the book).

I think there's a lot of merit in starting data science courses with nicely curated data (e.g., everything is correctly typed), and Parquet may be the best form of this for most purposes. I think too many analysis workflows start with "uncurated" data and I think the *mise en place* of data analysis would be to the separate data curation from analysis. (I wrote about this [here](https://github.com/iangow/notes/blob/main/import_sirca.pdf); the context is Australian, but the principles seem universal.)
