### ISSUE TITLE
Investigate time zones

### ISSUE THREAD

**Issue by iangow** [iangow/wrds2pg#41]
This would require asking WRDS to tell us what time zone data in various tables is represented. Armed with that information, it should be possible to have SAS emit the data with embedded time zone information.

**Comment by iangow** [comment]
2fc4e24 added support for time zones.

**Comment by iangow** [comment]
The timestamps in tables in `rpa` are in UTC, which is the default for the new argument `tz` for `wrds_update()`.

The timestamps in tables in `audit` are derived from SEC EDGAR data, which appear to be in US Eastern Time (see [here](https://money.stackexchange.com/questions/140481/what-is-the-time-zone-of-the-events-featured-by-the-sec) and [here](https://www.law.cornell.edu/cfr/text/17/232.13)). So I have started to update the scripts for `audit` (see [here](https://github.com/iangow/wrds_pg/commit/d8b11f7fc39d85b1842bb5a59359c86df829fbf0), for example).

**Comment by iangow** [comment]
Current status:

- `wrds_update()`: See above. Basically, the time zone is set in connecting to PostgreSQL.
- `wrds_update_pq()`: It seems that parquet files store timestamps in epoch form. These get read by (for example) R as timestamps. But the conversion to epoch will be off because the original timestamps are likely to be assumed to be in UTC. For `audit` data they are `America/New_York` (`America/Toronto`?) and so some fix would be needed in the `csv_to_pq()` function.
- `wrds_update_csv()`: This would be a bit trickier, as these files are piped directly from WRDS SAS to CSV files. So setting the timezone in SAS and then exporting time zone information would be the solution. This might be a better approach than the PostgreSQL approach above (it might even solve the `wrds_update_pq()` issue). I will look into it.

**Comment by iangow** [comment]
Setting time zones in SAS: [here](https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/nlsref/n0px72paaaqx06n1ozps024j78cl.htm#p13xc4wkxldkeen13w6lg4oxnufw)

**Comment by iangow** [comment]
Exploratory notebook [here](https://github.com/iangow/wrds2pg/blob/master/tz_sas.ipynb).

@EvanJo Do you rely on any timestamp data from WRDS?

It seems I can set things up right at source (`PROC EXPORT` in SAS) so that PostgreSQL, parquet, and CSVs could all have proper timestamps in the correct time zone (parquet is epoch under the hood, but current code assumes timestamps are in UTC). (The expectation would be that a user would figure out the time zone for a data set and provide it to the function called (default `tz='UTC'`). For [Audit Analytics](https://github.com/iangow/wrds_pg/blob/master/audit/readme.md), it's `America/New_York`; for [RavenPack](https://github.com/iangow/wrds_pg/blob/master/rpa/update_rpa.py) [`rpa`], it's UTC.)

For now I only have this functionality in `wrds_update()` (PostgreSQL).

**Comment by iangow** [comment]
I think this is done. See [here](https://github.com/iangow/wrds2pg/blob/master/tz_test.ipynb) for details.

**Comment by EvanJo** [comment]
Thanks a ton! I don't rely on the WRDS timestamps. Currently I use the CSV route mostly for teaching, especially when time doesn't permit going the SQL route.

Current version looks great!

**Comment by iangow** [comment]
With the new version, you can specify the time zone of the underlying data (e.g., `America/New_York` for Audit Analytics) and the time zone will be embedded into the CSV. Default is to assume UTC. Since the comment above, I have implemented this in all three functions, including `wrds_update_csv()` (it's all being done by SAS).
