### ISSUE TITLE
Understand difference between `fpath` and `rpath`.

### ISSUE THREAD

**Issue by iangow** [iangow/wrds2pg#44]

**Comment by iangow** [comment]
@jingyujzhang Do you recall the difference between `fpath` and `rpath`?

**Comment by jingyujzhang** [comment]
I don't recall the difference off the top of my head. It seems that they are the same. Starting from the main function `wrds_update`, `rpath` first appears separately in `get_modified_str`, which calls `proc_contents`. Other than that, `rpath` and `fpath` are treated in the same way in other functions. Replacing `rpath` with `fpath` won't change the results.

It's possible that the original intent was to distinguish between the absolute path and the relative path. However, the code seems to be missing the necessary steps to obtain the current working directory, which is crucial for converting `rpath` into `fpath`.

**Comment by iangow** [comment]
@jingyujzhang Thanks. Yes, there are better ways to handle relative paths and probably no need for a separate argument. I would have to do some set-up to be able to test this code on WRDS (I don't have access to SAS otherwise).
