### ISSUE TITLE
Update PyPI version

### ISSUE THREAD

**Issue by iangow** [iangow/wrds2pg#9]
@jingyujzhang Do you know how to do this? Perhaps if you add instructions here it would be great.

**Comment by iangow** [comment]
@jingyujzhang I *cannot* update the [PyPI](https://pypi.org) project. I think you need to give me access (my ID is `iangow` on that system).

```
igowmbp15:wrds2pg igow$ python3 -m twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: iangow
Enter your password: 
Uploading wrds2pg-0.1.17-py3-none-any.whl
100%|██████████████████████████████████████| 16.3k/16.3k [00:03<00:00, 4.92kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 403 Client Error: The user 'iangow' isn't allowed to upload to project 'wrds2pg'. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/
```

**Comment by jingyujzhang** [comment]
@iangow : I added you as the project owner. The instructions can be found [here](https://github.com/iangow/wrds2pg/issues/1#issuecomment-484989607).

**Comment by iangow** [comment]
@jingyujzhang Thanks. I deleted the older versions, as these had higher version numbers. The new version (`0.1.17`) is much better than the older ones.

**Comment by jingyujzhang** [comment]
@iangow: Do I need to update the `README`?

**Comment by iangow** [comment]
> @iangow: Do I need to update the `README`?

No, I already did that.
